### 1.  Assign your Name to variable name and Age to variable age. Make a Python program that prints your name and age.

In [6]:
name = 'Richa Rai'
age = 20
print('My name is ',name, 'and I am ', age, ' years old.')

My name is  Richa Rai and I am  20  years old.


### 2.  X="Datascience is used to extract meaningful insights." Split the string  

In [7]:
X = 'Datascience is used to extract meaningful insights.'
X.split()

['Datascience', 'is', 'used', 'to', 'extract', 'meaningful', 'insights.']

### 3. Make a function that gives multiplication of two numbers.

In [10]:
x = 25
y = 35
z = x*y
print('product of 2 numbers', x, ' and', y, ' is', z)

product of 2 numbers 25  and 35  is 875


### 4. Create a Dictionary of 5 States with their capitals. also print the keys and values. 

In [12]:
Dictionary = {'States':['Uttar Pradesh','Bihar','Haryana','Sikkim','Madhya Pradesh'],'Capital':['Lucknow','Patna','Chandigarh','Gangtok','Bhopal']}
print(Dictionary)

{'States': ['Uttar Pradesh', 'Bihar', 'Haryana', 'Sikkim', 'Madhya Pradesh'], 'Capital': ['Lucknow', 'Patna', 'Chandigarh', 'Gangtok', 'Bhopal']}


In [13]:
Dictionary.keys()


dict_keys(['States', 'Capital'])

In [14]:
Dictionary.values()

dict_values([['Uttar Pradesh', 'Bihar', 'Haryana', 'Sikkim', 'Madhya Pradesh'], ['Lucknow', 'Patna', 'Chandigarh', 'Gangtok', 'Bhopal']])

### 5. Create a list of 1000 numbers using range function

In [16]:
import numpy as np
np.arange(start = 1, stop = 1001)

array([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
         23,   24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
         34,   35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
         45,   46,   47,   48,   49,   50,   51,   52,   53,   54,   55,
         56,   57,   58,   59,   60,   61,   62,   63,   64,   65,   66,
         67,   68,   69,   70,   71,   72,   73,   74,   75,   76,   77,
         78,   79,   80,   81,   82,   83,   84,   85,   86,   87,   88,
         89,   90,   91,   92,   93,   94,   95,   96,   97,   98,   99,
        100,  101,  102,  103,  104,  105,  106,  107,  108,  109,  110,
        111,  112,  113,  114,  115,  116,  117,  118,  119,  120,  121,
        122,  123,  124,  125,  126,  127,  128,  129,  130,  131,  132,
        133,  134,  135,  136,  137,  138,  139,  140,  141,  142,  143,
        144,  145,  146,  147,  148,  149,  150,  1

###  6. Create an identity matrix of dimension 4 by 4

In [17]:
i =  np.eye(4)
print(i)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### 7. Create a 3x3 matrix with values ranging from 1 to 9

In [20]:
m = np.arange(1,10)
n = m.reshape(3,3)
print(n)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


###  8. Create 2 similar dimensional array and perform sum on them

In [35]:
arr1 = np.arange(15, 24)
arr1 = arr1.reshape(3,3)
print('1st array: \n',arr1)

arr2 = np.arange(38,56,2)
arr2 = arr2.reshape(3,3)
print('\n2nd array: \n',arr2)

     

1st array: 
 [[15 16 17]
 [18 19 20]
 [21 22 23]]

2nd array: 
 [[38 40 42]
 [44 46 48]
 [50 52 54]]


In [40]:
arr3 = np.add(arr1,arr2)
print('Sum of 1st array and 2nd array is: \n', arr3)

Sum of 1st array and 2nd array is: 
 [[53 56 59]
 [62 65 68]
 [71 74 77]]


### 9. Generate the series of dates from 1st Feb, 2023 to 1st March, 2023 (both inclusive)


In [41]:
import pandas as pd
dRange = pd.date_range(start ='2-1-2023', end ='3-1-2023', freq ='24H')
print(dRange)

DatetimeIndex(['2023-02-01', '2023-02-02', '2023-02-03', '2023-02-04',
               '2023-02-05', '2023-02-06', '2023-02-07', '2023-02-08',
               '2023-02-09', '2023-02-10', '2023-02-11', '2023-02-12',
               '2023-02-13', '2023-02-14', '2023-02-15', '2023-02-16',
               '2023-02-17', '2023-02-18', '2023-02-19', '2023-02-20',
               '2023-02-21', '2023-02-22', '2023-02-23', '2023-02-24',
               '2023-02-25', '2023-02-26', '2023-02-27', '2023-02-28',
               '2023-03-01'],
              dtype='datetime64[ns]', freq='24H')


### 10. Given a dictionary, convert it into corresponding dataframe and display it
dictionary = {'Brand': ['Maruti', 'Renault', 'Hyndai'], 'Sales' : [250, 200, 240]}

In [42]:
import pandas as pd

dictionary = {'Brand': ['Maruti', 'Renault', 'Hyndai'], 'Sales': [250, 200, 240]}

df = pd.DataFrame(dictionary)

print(df)

     Brand  Sales
0   Maruti    250
1  Renault    200
2   Hyndai    240
